import { BN } from "bn.js";

export const VDXF_OBJECT_RESERVED_BYTE_I_ADDR = new BN(102, 10);
export const VDXF_OBJECT_RESERVED_BYTE_VDXF_ID_STRING = new BN(103, 10);
export const VDXF_OBJECT_RESERVED_BYTE_ID_OR_CURRENCY = new BN(104, 10);

export const DATA_DESCRIPTOR_VDXF_ORDINAL = new BN(0, 10);
export const VERUSPAY_INVOICE_DETAILS_VDXF_ORDINAL = new BN(1, 10);
export const AUTHENTICATION_REQUEST_VDXF_ORDINAL = new BN(2, 10);
export const AUTHENTICATION_RESPONSE_VDXF_ORDINAL = new BN(3, 10);
export const IDENTITY_UPDATE_REQUEST_VDXF_ORDINAL = new BN(4, 10);
export const IDENTITY_UPDATE_RESPONSE_VDXF_ORDINAL = new BN(5, 10);
export const PROVISION_IDENTITY_DETAILS_VDXF_ORDINAL = new BN(6, 10);
export const APP_ENCRYPTION_REQUEST_VDXF_ORDINAL = new BN(7, 10);
export const APP_ENCRYPTION_RESPONSE_VDXF_ORDINAL = new BN(8, 10);
export const DATA_PACKET_REQUEST_VDXF_ORDINAL = new BN(9, 10);
export const USER_DATA_REQUEST_VDXF_ORDINAL = new BN(10, 10);
export const DATA_RESPONSE_VDXF_ORDINAL = new BN(11, 10);
