import { BN } from "bn.js";

export const VDXF_OBJECT_RESERVED_BYTE_I_ADDR = new BN(102, 10);
export const VDXF_OBJECT_RESERVED_BYTE_VDXF_ID_STRING = new BN(103, 10);
export const VDXF_OBJECT_RESERVED_BYTE_ID_OR_CURRENCY = new BN(104, 10);

export const VDXF_ORDINAL_DATA_DESCRIPTOR = new BN(0, 10);
export const VDXF_ORDINAL_VERUSPAY_INVOICE = new BN(1, 10);
export const VDXF_ORDINAL_LOGIN_REQUEST = new BN(2, 10);
export const VDXF_ORDINAL_LOGIN_RESPONSE = new BN(3, 10);
export const VDXF_ORDINAL_IDENTITY_UPDATE_REQUEST = new BN(4, 10);
export const VDXF_ORDINAL_IDENTITY_UPDATE_RESPONSE = new BN(5, 10);
export const VDXF_ORDINAL_PROVISION_IDENTITY_DETAILS = new BN(6, 10);

export const VDXF_ORDINAL_APP_ENCRYPTION_REQUEST_DETAILS = new BN(8, 10);
export const VDXF_ORDINAL_USER_SPECIFIC_DATA_PACKET = new BN(10, 10);
export const VDXF_ORDINAL_USER_DATA_REQUEST = new BN(12, 10);
export const VDXF_ORDINAL_DATA_DESCRIPTOR_RESPONSE = new BN(13, 10);
